[SPBU-21.B10] Task 1.1 Татьяненко Алексей
alexdtat/SPbU-Homework-1-semester pull request #1
Opened 2021-09-14 12:52 UTC by alexdtat

Solution to the first task added.

2021-09-15 17:46 UTC, SpirinEgor requested changes

2021-09-15 17:46 UTC, SpirinEgor commented on homework1/task_1.c
> +void divisionWithRemainder(int a, int b)
a и b совсем не говорящие имена. Они не передают никакой семантики о хранящихся значениях

2021-09-15 17:46 UTC, SpirinEgor commented on homework1/task_1.c
> +    printf("%d %c %d %c %d %c %d %c", a, '/', b, '=', quotient, '(', remainder, ')');
Необходимо разделять часть с вводом и выводом от логики программы. А у тебя вообще что-то странное -- числа на вход поступают как аргументы, а результат печатается в терминал.

2021-09-18 13:57 UTC, SpirinEgor requested changes

2021-09-18 13:57 UTC, SpirinEgor commented on homework1/task_1.c
> +bool divisionWithRemainder(int dividend, int divisor, int* quotient, int* remainder)
Это очень классное решение, но есть одно "но". В задании ничего не было сказано про остаток. Поэтому хочется увидеть функцию, которая может принять 2 числа и ссылку на целое. С остатком есть 2 пути: убрать его вообще или сделать параметром с дефолтным значением. Если стоит дефолтное значение, то значение остатка туда записывать не надо.

2021-09-19 09:43 UTC, alexdtat commented on homework1/task_1.c
> +bool divisionWithRemainder(int dividend, int divisor, int* quotient, int* remainder)
> Это очень классное решение, но есть одно "но". В задании ничего не было сказано про остаток. Поэтому хочется увидеть функцию, которая может принять 2 числа и ссылку на целое. С остатком есть 2 пути: убрать его вообще или сделать параметром с дефолтным значением. Если стоит дефолтное значение, то значение остатка туда записывать не надо.

Насколько я знаю, в C есть какие-то проблемы со значениями аргументов функции по умолчанию (вплоть до необходимости использования макросов), так что лучше уберу.

2021-09-22 10:19 UTC, SpirinEgor requested changes

2021-09-22 10:19 UTC, SpirinEgor commented on homework1/task_1.c
> +        return 0;
Но ведь есть false...

2021-09-22 10:19 UTC, SpirinEgor commented on homework1/task_1.c
> +    return 1;
А тут есть true...

2021-09-23 10:44 UTC, SpirinEgor approved these changes

2021-09-23 10:45 UTC, merged