[SPBU-21.B10] Task 1.2 Татьяненко Алексей
alexdtat/SPbU-Homework-1-semester pull request #2
Opened 2021-09-14 14:19 UTC by alexdtat

Solution to the second task added.

2021-09-18 14:08 UTC, SpirinEgor requested changes

2021-09-18 14:08 UTC, SpirinEgor commented on homework1/task_2.c
> +        if (array[i] > maxPair || thereExistsMaxPair) {
А тут не надо разыменовать указатель?

2021-09-19 09:19 UTC, alexdtat commented on homework1/task_2.c
> +        if (array[i] > maxPair || thereExistsMaxPair) {
> А тут не надо разыменовать указатель?

Так, вроде бы, оно и так корректно работает.

2021-09-22 10:21 UTC, SpirinEgor approved these changes

2021-09-22 10:21 UTC, merged