[SPBU-21.B10] Task 2.1 Татьяненко Алексей
alexdtat/SPbU-Homework-1-semester pull request #6
Opened 2021-09-27 09:28 UTC by alexdtat

The LinkedMap library has been added.

2021-09-28 07:55 UTC, ArtyomLobanov requested changes

2021-09-28 07:55 UTC, ArtyomLobanov commented on homework2/task_1.c
> +    bufferString = calloc(map->keySize, sizeof(char));
Если вы создёте объект в начале метода, а конце этого же метода его уничтожаете, то это верный признак того, что объект следовало выделять на стеке, а не на куче. Это проще, быстрее работает и нет шансов случайно допустить утечку памяти, если потом вдруг у метода появится ещё она точка выхода (return в каком-нибудь if-е).

2021-09-28 07:55 UTC, ArtyomLobanov commented on homework2/task_1.c
> +                appendElement(map, createNewElement(bufferString, map->keySize));
Как-то много логики вы оставляете на откуп пользователю вашего контейнера. Давайте завернём эту проверку в метод put – пусть он автоматически создаёт новые элементы при необходимости.

2021-09-28 07:55 UTC, ArtyomLobanov commented on homework2/task_1.c
> +                bufferString[i] = '\0';
Это лишнее. Функция fscanf на следующей итерации запишет нулевой символ после прочитанных данных, а всё что идёт после нулевого символа уже не имеет значение.

2021-09-28 07:55 UTC, ArtyomLobanov commented on homework2/task_1.c
> +    char* resultsFilePath = calloc(255, sizeof(char));
Опять же можно было выделить на стеке

2021-09-28 07:55 UTC, ArtyomLobanov commented on homework2/task_1.c
> +    scanf("%s", resultsFilePath);
Ожидалось, что пути к файлам передаются программе в качестве аргументов.
`program_name.exe text.txt result.csv`

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +}
В `string.h` есть функция `int strcmp(const char *, const char *)`. Она может упростить вам жизнь

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +        newElement->key[i] = data[i];
`strcpy` вам в помощь

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +    }
break или return

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +    }
Вот этот вот цикл с поиском нужного элемента повторяется минимум 3 раза. Давайте вынесем логику поиска элемента в отдельную функцию.

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +    }
А почему тут внезапно while, хотя раньше всегда for использовали?

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +    nextElement = elementForDeletion->nextElement;
Так и почему это в одну строчку не написать?

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +    free((char*)elementForDeletion->key);
А зачем здесь этот каст к `char*`? Поле key и так же объявлено как `char*`.

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +    elementForDeletion->nextElement = NULL;
С учётом того, что в следующей строчке вы уничтожаете `elementForDeletion`, обнуление указателя выглядит бессмысленно.

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +        firstNotRemovedElement = deleteElementAndGetNext(mapElement);
А зачем множить сущности?
```cpp
for (LinkedMapElement* element = map->head; element; element = deleteElementAndGetNext(element));
```

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +    free(map);
Если расскажете свою мотивацию обнулять ссылки перед очисткой памяти, то можете оставить тут всё как есть.

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.h
> +} LinkedMap;
Кстати, порядок элементов нам не важен, поэтому можно было обойтись одной ссылкой на голову списка и добавлять новые элементы в начало. Это немножко упростило бы код. Но ваша реализация тоже имеет право на жизнь.

2021-09-28 07:55 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.h
> +    int keySize;
Зачем LinkedMap знать ограничение на длину слов? Память под хранение ключей можно выделять исходя из фактического размера строк, а сравнивать буфферы посимвольно вообще странная затея. С точки зрения логики работы строк в C, буфферы "abacaba\0trash" и "abacaba\0\0\0\0\0" содержат одинаковые значения. У вас эта логика нарушается. Плюс вся логика работы структуры данных сломается, если постфактум уменьшить keySize. Тогда в структуре данных может оказаться несколько равных (по первым keySize символам) ключей.  А если постфактум увеличить keySize, то можно поймать ошибку сегментации.

2021-10-01 19:18 UTC, alexdtat commented on library/LinkedMap/LinkedMap.h
> +    int keySize;
> Зачем LinkedMap знать ограничение на длину слов? Память под хранение ключей можно выделять исходя из фактического размера строк, а сравнивать буфферы посимвольно вообще странная затея. С точки зрения логики работы строк в C, буфферы "abacaba\0trash" и "abacaba\0\0\0\0\0" содержат одинаковые значения. У вас эта логика нарушается. Плюс вся логика работы структуры данных сломается, если постфактум уменьшить keySize. Тогда в структуре данных может оказаться несколько равных (по первым keySize символам) ключей. А если постфактум увеличить keySize, то можно поймать ошибку сегментации.

Я думал в дальнейшем использовать эту же структуру (немного доработанную) для второй задачи, где выделение памяти под 127 char-элементов в key избыточно, но не вижу более удобного способа задавать фиксированный размер строки. А как для фактического размера строк выделять? Мне же нужен какой-то буфер для того, чтобы можно было записать туда из файла строку и считать её размер (а размер памяти для буфера я не знаю, если нигде не указывать его специально). Либо же посимвольно считать, а потом выделять память и считывать слово целиком, что значительно менее удобно.

Буфер "abacaba\0trash", как я понимаю, здесь не появляются, потому что при выделении через calloc всегда нулями инициализируется массив, а при записи таких "пробелов" не возникает.

2021-10-01 19:20 UTC, alexdtat commented on homework2/task_1.c
> +                bufferString[i] = '\0';
> Это лишнее. Функция fscanf на следующей итерации запишет нулевой символ после прочитанных данных, а всё что идёт после нулевого символа уже не имеет значение.


Если оставлять через calloc реализацию, то программа будет многие слова записывать повторно, если нет этого цикла. Для выделения на стеке пока не проверял.

2021-10-01 19:22 UTC, alexdtat commented on homework2/task_1.c
> +    bufferString = calloc(map->keySize, sizeof(char));
> Если вы создёте объект в начале метода, а конце этого же метода его уничтожаете, то это верный признак того, что объект следовало выделять на стеке, а не на куче. Это проще, быстрее работает и нет шансов случайно допустить утечку памяти, если потом вдруг у метода появится ещё она точка выхода (return в каком-нибудь if-е).

А как мне для буфера установить размер без keySize, если выделять на стеке? Я могу, конечно, 127 символов сделать, но не будет ли это помехой при дальнейшем использовании библиотеки (даже в той же второй задаче)?

2021-10-01 19:46 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.h
> +    int keySize;
Все эти разговоры про длину строки должны лежать в плане чтения файла и решаться в файле task_2.c
А у LinkedMap интерфейс простой – она получает ключ в виде указателя char* на какую-то область памяти, в которой записана строка неизвестной длины, оканчивающася нулевым сиволом. В LinkedMapElement нужно сохранить копию ключа для дальнйшего использования. Т.к. длина строки заранее не известна и отличается от ключа к ключу, то выделять память нужно динамически, на куче. Скажем, пришёл вам новый ключ "Hello\0". Вы можете посчитать (или использовать стандартную функцию strlen), что данный ключ имеет 5 смысловых символов, да плюс ещё нулевой символ конца строки. Значит для хранения копии нужно выделить на куче место под 6 char-ов. В это нововыделенную память копируем данные из ключа, а ссылку сохраняем в LinkedMapElement. Главное, не забыть в конце аккуратно очистить память.

2021-10-02 09:50 UTC, ArtyomLobanov commented on homework2/task_1.c
> +                bufferString[i] = '\0';
Это потому что у вас сравнение строк не конвенциональное. 
```cpp
bool stringsAreSimilar(const char* string1, const char* string2, int stringsSize)
{
    for (int i = 0; i < stringsSize; i++) {
        if (string1[i] != string2[i])
            return false;
    }
    return true;
}
```
Раз уж принято, что символ \0 ознаменовывает конец строки, то строки "aba\0aaa" и "aba\0bbb" должны при сравнении получаться одинаковыми. Следовательно функция сравнения должна выглядеть как-то так:
```cpp
bool stringsAreSimilar(const char* first, const char* second)
{
    for (int i = 0; first[i] != '\0' && second[i] != '\0'; i++) {
        if (first[i] != second[i])
            return false;
    }
    return true;
}
```
или используя механику указателей
```cpp
bool stringsAreSimilar(const char* first, const char* second)
{

    while (*first != '\0' && *first == *second) {
        first++;
        second++
    }
    return *first == *second;
}
```

2021-10-07 14:04 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +    }
Во-первых, скобки не по стайлгайду. Во-вторых, в цикле должно быть не `elementForDeletion = elementForDeletion->nextElement`, а `currentElement = currentElement ->nextElement`

2021-10-07 14:11 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +        map->head = nextElement;
Просто else казалось бы. Если previousElement это NULL (т.е. удаляем первый элемент), то map->head в любом случае нужно обновить,  иначе там будет лежать ссылка на очищенную область памяти. А уж есть следующий элемент или нет – уже не так важно

2021-10-07 14:14 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +            map->tail = previousElement;
Опять же, если nextElement это NULL, то значит удаляем последний элемент списка => обязательно нужно обновить map->tail, дабы не хранить указатели на очищенную память. А у вас это произойдёт только если мы удаляем не первый элемент.

2021-10-09 16:38 UTC, ArtyomLobanov commented on homework2/task_1.c
> +        printf("FILE OPENING ERROR! The error's code (errno):\t%d\n", errno);
Выводите в main-е.

2021-10-11 14:51 UTC, ArtyomLobanov commented on homework2/task_1.c
> +    int resultsFileErrorCode = writeLinkedMapIntoFile(myMap, argv[2]);
По-хорошему, если прочитать файл не удалось, то и файл с результатами создавать/перезаписывать не стоит. Что-то осмысленное мы туда записать всё равно не сможем, а какие-то хранящиеся там данные пользователю можем испортить.

2021-10-11 14:53 UTC, ArtyomLobanov commented on library/LinkedMap/LinkedMap.c
> +        findElementByKey(map, userKey)->value = userValue;
По сути метод findElementByKey вызывается здесь два раза, а работает он довольно долго – за линейное от размера структуры время. Можно было обойтись одним вызовом:
```cpp
MapElement* element = findElementByKey(map, userKey);
if (element)
    element->value = value;
else
    appendElement(map, createNewElement(userKey, 1));
```

2021-10-11 14:54 UTC, merged